server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carbon_footprint_db
    username: postgres
    password: nincs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 20MB
