name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build & Deploy Spring Boot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: "corretto"
          java-version: 23

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build App
        run: |
          mvn clean
          mvn -B package --file pom.xml
          


